Web/SuperZapatosWeb/SuperZapatosWeb/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperZapatosWeb.Models;
using System.Configuration;
using System.Net.Http;
using System.Text;
using System.Net.Http.Headers;
using System.Web.Script.Serialization;
using SuperZapatosWeb.DAL;

namespace SuperZapatosWeb.Controllers
{
    public class ArticlesController : Controller
    {
        //private SuperZapatosWebContext db = new SuperZapatosWebContext();

        // GET: /Articles/
        public ActionResult Index()
        {
            ArticleResponse response = SuperZapatosAPI.GetArticleAPI("services/articles/");

            return View(response.articles);
        }

        // GET: /Articles/Create
        public ActionResult Create()
        {
            //Get Stores to fill the dropdown
            StoreResponse responseStore = SuperZapatosAPI.GetStoreAPI("services/stores/");
            
            List<SelectListItem> listItems = new List<SelectListItem>();
            foreach (var item in responseStore.stores)
            {
                SelectListItem newItem = new SelectListItem(){
                    Text = item.Name,
                    Value=item.Id.ToString()
                };
                listItems.Add(newItem);
                
            }
            ViewBag.Stores = listItems;

            return View();
        }

        // POST: /Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Description,Price,TotalInShelf,TotalInVault,StoreId")] ArticleModel articlemodel)
        {
            if (ModelState.IsValid)
            {
                ArticleResponse response = SuperZapatosAPI.CallArticleAPI("services/createArticle", articlemodel);

                return RedirectToAction("Index");
            }

            return View(articlemodel);
        }

        // GET: /Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ArticleResponse response = SuperZapatosAPI.GetArticleAPI("services/articles/", id.ToString());

            //Get Stores to fill the dropdown
            StoreResponse responseStore = SuperZapatosAPI.GetStoreAPI("services/stores/");

            List<SelectListItem> listItems = new List<SelectListItem>();
            foreach (var item in responseStore.stores)
            {
                SelectListItem newItem = new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                };
                listItems.Add(newItem);

            }
            ViewBag.Stores = listItems;

            return View(response.articles[0]);
        }

        // POST: /Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Description,Price,TotalInShelf,TotalInVault,StoreId")] ArticleModel articlemodel)
        {
            if (ModelState.IsValid)
            {
                ArticleResponse response = SuperZapatosAPI.CallArticleAPI("services/updateArticle", articlemodel);

                return RedirectToAction("Index");
            }
            return View(articlemodel);
        }

        // GET: /Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ArticleResponse response = SuperZapatosAPI.GetArticleAPI("services/articles/", id.ToString());

            return View(response.articles[0]);
        }

        // POST: /Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IdentifierModel ident = new IdentifierModel();
            ident.id = id.ToString();
            ArticleResponse response = SuperZapatosAPI.CallArticleAPI("services/deleteArticle", ident);

            return RedirectToAction("Index");
        }

    }
}

Web/SuperZapatosWeb/SuperZapatosWeb/Controllers/HomeController.cs
using SuperZapatosWeb.DAL;
using SuperZapatosWeb.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SuperZapatosWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            StoreResponse responseStore = SuperZapatosAPI.GetStoreAPI("services/stores/");
            ArticleResponse responseArticle = SuperZapatosAPI.GetArticleAPI("services/articles/");

            ViewBag.Stores = responseStore.stores;
            ViewBag.Articles = responseArticle.articles;
            return View();
        }

        public ActionResult ArticlesByStore(string id)
        {
            IdentifierModel ident = new IdentifierModel();
            ident.id = id.ToString();
            ArticleResponse responseArticle = SuperZapatosAPI.GetArticleAPI("services/articles/stores/", id);
            if (responseArticle.status != null && responseArticle.status.Equals("false"))
            {
                ViewBag.Response = responseArticle;
            }
            return View(responseArticle.articles);
        }
    }
}

Web/SuperZapatosWeb/SuperZapatosWeb/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperZapatosWeb.Models;
using System.Configuration;
using System.Net.Http;
using System.Text;
using System.Net.Http.Headers;
using System.Web.Script.Serialization;
using SuperZapatosWeb.DAL;

namespace SuperZapatosWeb.Controllers
{
    public class StoresController : Controller
    {
        // GET: /Stores/
        public ActionResult Index()
        {
            StoreResponse response = SuperZapatosAPI.GetStoreAPI("services/stores/");

            return View(response.stores);
        }

        // GET: /Stores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Stores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Address")] StoreModel storemodel)
        {
            if (ModelState.IsValid)
            {
                StoreResponse response = SuperZapatosAPI.CallStoreAPI("services/createStore", storemodel);
                
                return RedirectToAction("Index");
            }

            return View(storemodel);
        }

        // GET: /Stores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            StoreResponse response = SuperZapatosAPI.GetStoreAPI("services/stores/", id.ToString());

            return View(response.stores[0]);
        }

        // POST: /Stores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Address")] StoreModel storemodel)
        {
            if (ModelState.IsValid)
            {
                StoreResponse response = SuperZapatosAPI.CallStoreAPI("services/updateStore", storemodel);

                return RedirectToAction("Index");
            }
            return View(storemodel);
        }

        // GET: /Stores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            StoreResponse response = SuperZapatosAPI.GetStoreAPI("services/stores/", id.ToString());

            return View(response.stores[0]);
        }

        // POST: /Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IdentifierModel ident = new IdentifierModel();
            ident.id = id.ToString();
            StoreResponse response = SuperZapatosAPI.CallStoreAPI("services/deleteStore", ident);

            return RedirectToAction("Index");
        }

    }
}

Web/SuperZapatosWeb/SuperZapatosWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web/SuperZapatosWeb/SuperZapatosWeb/Views/Home/ArticlesByStore.cshtml
@model IEnumerable<SuperZapatosWeb.Models.ArticleModel>

@{
    ViewBag.Title = "Articles By Store";
}

<h2>Articles By Store</h2>

@if (ViewBag.Response != null)
{
    SuperZapatosWeb.Models.ArticleResponse responseArticle = ViewBag.Response;
    <div class="col-lg-4">
        <div class="bs-component">
            <div class="alert alert-dismissible alert-danger">
                <strong>Error:</strong> @responseArticle.error_code / Message: @responseArticle.error_msg
            </div>
        </div>
    </div>
}
else
{
    if (Model.Count() > 0)
    {
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalInShelf)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalInVault)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StoreId)
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalInShelf)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalInVault)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Store.Name)
                        </td>
                    </tr>
                }

            </table>
        </div>
    }
    else
    {
        <div class="col-lg-4">
            <div class="bs-component">
                <div class="alert alert-dismissible alert-info">
                    <strong>Ups!</strong> There are not articles in this store.
                </div>
            </div>
        </div>
    }
}

Web/SuperZapatosWeb/SuperZapatosWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web/SuperZapatosWeb/SuperZapatosWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Super Zapatos";
    List<SuperZapatosWeb.Models.StoreModel> stores = ViewBag.Stores;
    List<SuperZapatosWeb.Models.ArticleModel> articles = ViewBag.Articles;
    
}

<script src="/Scripts/jquery-1.10.2.js" type="text/javascript"></script>      

<div class="jumbotron">
    <h1>Super Zapatos</h1>
    <p class="lead">Welcome to the shoe store Super Zapatos.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Stores</h2>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Address
                    </th>
                    <th>Articles</th>
                </tr>

                @foreach (var item in stores)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>@Html.ActionLink("See Articles", "ArticlesByStore", new {id = item.Id})</td>
                    </tr>
                }

            </table>
        </div>
        <p>
            @Html.ActionLink("See Details", "Index", "Stores")
        </p>
    </div>
    <div class="col-md-8">
        <h2>Articles</h2>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Store
                    </th>
                </tr>

                @foreach (var item in articles)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Store.Name)
                        </td>
                    </tr>
                }

            </table>
            </div>
            <p>
                @Html.ActionLink("See Details", "Index", "Articles")
            </p>
        </div>

    <div id="stores"></div>
    
</div>

<script type="text/javascript">
    //var hostUrl = "http://localhost:2815";
    //var apiUrl = '/services/test/';

    //$(document).ready(function () {
    //    GetAllStores();
    //});

    //function GetAllStores() {
    //    $.ajax({
    //        url: hostUrl + apiUrl,
    //        type: 'GET',
    //        dataType: 'jsonp',
    //        username: "my_user",
    //        password: "my_password",
    //        xhrFields: {
    //            withCredentials: true
    //        },
    //        crossDomain: true,
    //        success: function (data) {
    //            debugger;
    //            DisplayStoreList(data);
    //        },
    //        error: function (x, y, z) {
    //            debugger;
    //            alert("error");
    //        }
    //    });
    //}
    //function DisplayStoreList(stores) {
    //    debugger;
    //    $("#stores").empty();
    //    var result = "<table><th>ID</th><th>Name</th><th>Address</th>";
    //    $.each(stores, function (index, store) {
    //        result += "<tr><td>" + store.Id + "</td><td> " + store.Name + "</td><td>"
    //            + store.Address + "</td></tr>";
    //    });
    //    result += "</table>";
    //    $("#stores").html(result);
    //}


</script>